#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainPanel;
                ref class CheckBox;
                ref class TextBlock;
                ref class AppBar;
            }
        }
    }
}

namespace App3
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ swapChainPanel;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ cbShowWireframe;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ cbShowLights;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ cbShowGrid;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbTitle;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbFileSize;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbVertex;
        private: ::Windows::UI::Xaml::Controls::AppBar^ bottomAppBar;
    };
}

